// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdj7lcmhHrjDaL36PBkvdNk3HJZ7wWp9s',
    appId: '1:413837160448:web:6e2bef320877ba7c5ba8e5',
    messagingSenderId: '413837160448',
    projectId: 'app-one-8c953',
    authDomain: 'app-one-8c953.firebaseapp.com',
    databaseURL: 'https://app-one-8c953-default-rtdb.firebaseio.com',
    storageBucket: 'app-one-8c953.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHNYgxK8bVjjkHphwDW21c3gksqXW89GY',
    appId: '1:413837160448:android:20e069dee050fb445ba8e5',
    messagingSenderId: '413837160448',
    projectId: 'app-one-8c953',
    databaseURL: 'https://app-one-8c953-default-rtdb.firebaseio.com',
    storageBucket: 'app-one-8c953.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdj7lcmhHrjDaL36PBkvdNk3HJZ7wWp9s',
    appId: '1:413837160448:web:b4d9e5d75d4439035ba8e5',
    messagingSenderId: '413837160448',
    projectId: 'app-one-8c953',
    authDomain: 'app-one-8c953.firebaseapp.com',
    databaseURL: 'https://app-one-8c953-default-rtdb.firebaseio.com',
    storageBucket: 'app-one-8c953.firebasestorage.app',
  );


}